/*
   RELATÓRIO UNIFICADO DE IMAGENS
   Oracle / WinThor

   Uma única saída contém:
   1) resumo do fornecedor (repetido em cada produto do fornecedor)
   2) dados do produto
   3) situação de atividade e imagem

   O Dashboard usa os campos de resumo para os KPIs e os campos do
   produto para a lista de produtos sem imagem.
*/

WITH BASE_PRODUTOS AS (
    SELECT
        PCPRODUT.CODPROD,
        PCPRODUT.CODFAB,
        PCPRODUT.DESCRICAO,
        PCPRODUT.CODAUXILIAR,
        PCPRODUT.CODAUXILIAR2,
        PCPRODUT.CODFORNEC,
        PCFORNEC.FORNECEDOR AS NOME_FORNECEDOR,
        PCPRODUT.DTEXCLUSAO,
        PCPRODUT.DIRFOTOPROD
    FROM PCPRODUT
    LEFT JOIN PCFORNEC
        ON PCFORNEC.CODFORNEC = PCPRODUT.CODFORNEC
    WHERE PCPRODUT.CODFORNEC IN (
        13, 28, 723, 1017, 1122, 1178, 1228, 2199,
        2478, 21, 2306, 1171, 2687, 2701, 2716,
        2685, 2724, 1894, 2615, 29, 1044, 1101,
        1187, 1233, 1253, 1424, 1844, 1861, 1895,
        2073, 2135, 2354, 2384, 2655, 1340, 2644,
        2666, 2211, 2023
    )
),

FORNECEDOR_STATS AS (
    SELECT
        CODFORNEC,
        COUNT(*) AS TOTAL_PRODUTOS,
        SUM(CASE WHEN DTEXCLUSAO IS NULL THEN 1 ELSE 0 END) AS TOTAL_ATIVOS,
        SUM(CASE WHEN DTEXCLUSAO IS NULL AND DIRFOTOPROD IS NOT NULL THEN 1 ELSE 0 END) AS PRODUTOS_COM_FOTOS,
        SUM(CASE WHEN DTEXCLUSAO IS NULL AND DIRFOTOPROD IS NULL THEN 1 ELSE 0 END) AS PRODUTOS_SEM_FOTOS
    FROM BASE_PRODUTOS
    GROUP BY CODFORNEC
)

SELECT
    B.CODPROD,
    B.CODFAB,
    B.DESCRICAO,
    B.CODAUXILIAR,
    B.CODAUXILIAR2,
    B.CODFORNEC,
    B.NOME_FORNECEDOR,

    FS.TOTAL_PRODUTOS,
    FS.TOTAL_ATIVOS,
    FS.PRODUTOS_COM_FOTOS,
    FS.PRODUTOS_SEM_FOTOS,

    CASE
        WHEN FS.TOTAL_ATIVOS > 0
        THEN ROUND(FS.PRODUTOS_COM_FOTOS * 100 / FS.TOTAL_ATIVOS, 2)
        ELSE 0
    END AS PERC_COM_FOTOS,

    CASE
        WHEN FS.TOTAL_ATIVOS > 0
        THEN ROUND(FS.PRODUTOS_SEM_FOTOS * 100 / FS.TOTAL_ATIVOS, 2)
        ELSE 0
    END AS PERC_SEM_FOTOS,

    CASE
        WHEN B.DTEXCLUSAO IS NULL THEN 1
        ELSE 0
    END AS ATIVO,

    CASE
        WHEN B.DTEXCLUSAO IS NOT NULL THEN 'INATIVO'
        WHEN B.DIRFOTOPROD IS NOT NULL THEN 'COM FOTO'
        ELSE 'SEM FOTO'
    END AS STATUS_IMAGEM

FROM BASE_PRODUTOS B
INNER JOIN FORNECEDOR_STATS FS
    ON FS.CODFORNEC = B.CODFORNEC

ORDER BY
    B.CODFORNEC,
    B.DESCRICAO,
    B.CODPROD;
